print("Hello world!")
my_name = input("What is your name: ")
print(my_name)
print("It is good to meet you, " + my_name + ".")
my_age = input("What is your age: ")
print("You will be, " + str(int(my_age) + 1) + " in a year.")
print("The length of your name is ")
print(len(my_name))
